### ISSUE TITLE
0.0.4版本的prometheus的缩容

### ISSUE THREAD

**Issue by solid-wang** [tkestack/kvass#15]
https://github.com/tkestack/kvass/issues/12#issuecomment-750003284
似乎并没有在0.0.4版本完成

**Comment by RayHuangCN** [comment]
sorry哈，0.0.4中高优先级修复了一些比较严重的bug，这些bug会影响正常使用 : )， 缩容预计在1月底就会发布。

**Comment by like-inspur** [comment]
@RayHuangCN 马上2月底了，问一下新版本何时发布，谢谢！

**Comment by RayHuangCN** [comment]
v0.0.5已支持缩容
