### ISSUE TITLE
coordinator中的config-reload容器似乎并没有什么用

### ISSUE THREAD

**Issue by solid-wang** [tkestack/kvass#16]
https://github.com/tkestack/kvass/blob/master/examples/coordinator.yaml
rancher/coreos-prometheus-config-reloader:v0.32.0似乎是帮助prometheus重载配置的，dockerhub中找到这个image但没发现用法或者代码仓库地址。
可以描述一下它的作用以及在kvass中的使用场景？

**Comment by RayHuangCN** [comment]
您好，config-reloader的作用是在配置变化的时候告知coordinator，coordinator也是需要更新内部配置文件相关的内容哦，比如需要根据新配置文件更新服务发现的配置 : )

**Comment by like-inspur** [comment]
各位好，我发现这个镜像的作用是读取默认配置和环境变量生成新配置，并调用reload接口触发coordinator加载新配置。如果coordinator没有使用环境变量，那么是否可以使用jimmidyson/configmap-reload:v0.5.0镜像，这个提供源代码且使用更方便
@solid-wang @RayHuangCN
