### ISSUE TITLE
target 分配支持某种亲和设置么

### ISSUE THREAD

**Issue by wanfuuyu** [tkestack/kvass#17]
在两个exporter 的指标有关联的情况下

比如 我同一个节点的 node_exporter 和. cadvisor 的采集尽量分配在同一个 prom 上， 这样prom 本地做 record rule 要省不少事情

**Comment by xiaozongyang** [comment]
+1，在不多引入一层 prom 的前提下，例如按 service 聚合，这种需求需要保证同一个 service 的 target 被一个 prom 采集

但是可能有个问题，如果按照 service 或者 node 之类的来做亲和性，很可能会超过单个 prom 的容量，还是没法完全解决 recording rule 的需求，看起再引入一层 prom 来做 federation 是必须的

**Comment by RayHuangCN** [comment]
目前还没有引入该特性的计划哦
