### ISSUE TITLE
静态配置中默认label保留目的是什么

### ISSUE THREAD

**Issue by like-inspur** [tkestack/kvass#23]
查看prometheus的静态配置，除了给指标使用的label外，还有一些默认label和__parm开头的label，保留目的是什么
![image](https://user-images.githubusercontent.com/18571465/108331780-11466e80-720a-11eb-933f-bae28a5824fe.png)
![image](https://user-images.githubusercontent.com/18571465/108331849-23281180-720a-11eb-8f71-9d1a2bbd593b.png)

**Comment by RayHuangCN** [comment]
您好，这几个label是用于sidecar识别抓取请求用的，__param的label会被prometheus加到请求参数里，从而传递给sidecar，sidecar用这些参数去配置文件里找到对应的job，利用job里的配置进行实际的采集(例如证书信息)

**Comment by like-inspur** [comment]
sidecar的拉取不能直接读取静态配置的target吗，你的意思是它必须依赖这些label才能找到对应job和target，从而完成拉取

**Comment by RayHuangCN** [comment]
因为请求过来的时候，只有url，并不知道是哪个job的抓取请求。

**Comment by like-inspur** [comment]
嗯，那我再看下sidecar的代码，理解下是怎么使用这些label的
