### ISSUE TITLE
When sidecar met some error and restart(like OOM kill), the targets may loss

### ISSUE THREAD

**Issue by GoneLikeAir** [tkestack/kvass#29]
When I testing kvass, sometimes kvass sidecar will be killed because of OOM, and then the targets scraped by that shard will loss.
According to the source code, coordinator will cache the targets info in 'scraping', the cache seems like never update anywhere. While sidecar encounter some error, the injected target will lost but coordinator will not know. 
I think kvass should keep the cache in coordinator and sidecar the same.

**Comment by RayHuangCN** [comment]
Shard need pvc to store local targets set.
