### ISSUE TITLE
分片缩容的闲置时间是否单独生效

### ISSUE THREAD

**Issue by like-inspur** [tkestack/kvass#31]
分片缩容讲到当分片被清空后，分片会变为闲置状态，经过一段时间后（等待分片数据被删除或者被上传至对象存储），分片被删除
请问如果设置了-shard.max-idle-time后，是不是也要等待prometheus分片数据被删除的时间，即选择二者的最大值
另外，prometheus分片被删除是指的内存中还是硬盘上删除

**Comment by RayHuangCN** [comment]
如果没有使用对象存储，则建议设置成数据存储时长，如果使用对象存储，则建议设置成落盘时间加上一些延迟，一般是3h。
这个需要使用者根据实际场景来选择

**Comment by like-inspur** [comment]
我现在的场景时，使用prometheus采集数据后，通过remote-write写入Influxdb，那这个时间就估算成远程写入完成的时间是吧

**Comment by RayHuangCN** [comment]
对，可以直接写得很短，如果是直接写remote wirter，那建议分片的删除时间和落盘时间都设置得比较短

**Comment by like-inspur** [comment]
嗯，明白了
