### ISSUE TITLE
Sidecar panic because of runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by GoneLikeAir** [tkestack/kvass#35]
When I deploy a new prometheus, I had met the error below. Is this a known bug?

**k8s version:**
1.16.6

**kvass version:**
tag 0.5

**Log:**
2021/03/04 07:30:41 http: panic serving 127.0.0.1:43278: runtime error: invalid memory address or nil pointer dereference
goroutine 680 [running]:
net/http.(*conn).serve.func1(0xc00099a000)
        /usr/local/go/src/net/http/server.go:1772 +0x139
panic(0x22a1580, 0x3e505f0)
        /usr/local/go/src/runtime/panic.go:973 +0x3e3
tkestack.io/kvass/pkg/sidecar.(*Proxy).ServeHTTP.func1(0xc000871480, 0xc0084105d6f1662b, 0x226bdee68e, 0x3e7a0a0, 0xc0008cfa58, 0xc0005dff20, 0xc0008cfa68, 0x2bbc780, 0xc00079a000)
        /Users/Gone/code/kvass/pkg/sidecar/proxy.go:90 +0x50
tkestack.io/kvass/pkg/sidecar.(*Proxy).ServeHTTP(0xc0005dff20, 0x2bbc780, 0xc00079a000, 0xc000802900)
        /Users/Gone/code/kvass/pkg/sidecar/proxy.go:113 +0x8b2
net/http.serverHandler.ServeHTTP(0xc0006de460, 0x2bbc780, 0xc00079a000, 0xc000802900)
        /usr/local/go/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc00099a000, 0x2bc5b00, 0xc00099c000)
        /usr/local/go/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2933 +0x35c

**Comment by RayHuangCN** [comment]
fixed in 0.0.6
