### ISSUE TITLE
Add support for vmagent

### ISSUE THREAD

**Issue by valyala** [tkestack/kvass#4]
[Vmagent](https://victoriametrics.github.io/vmagent.html) accepts Prometheus scrape configs. It would be great if kvass could balance load among a group of vmagents too. Vmagent exposes various metrics at `/metrics` page, wchich could be used during rebalancing decisions. See https://victoriametrics.github.io/vmagent.html#monitoring

**Comment by gaocegege** [comment]
Thanks for the issue!

We haven't gotten around to it yet. If you put forth a proposed design, we'd be happy to take a look.

👍

**Comment by RayHuangCN** [comment]
@valyala Great! i will try this in later version :- )

**Comment by valyala** [comment]
FYI, `vmagent` gained native support for sharding scrape targets among a cluster of `vmagent` instances - see [these docs](https://docs.victoriametrics.com/vmagent.html#scraping-big-number-of-targets).

**Comment by zhangsheng9** [comment]
> [@valyala](https://github.com/valyala) Great! i will try this in later version :- )

请问下目前支持对vmagent动态分片了吗

**Comment by husoule** [comment]
您好，您的邮件我已经收到。
