### ISSUE TITLE
增大max-series后prometheus副本没有实现缩容

### ISSUE THREAD

**Issue by like-inspur** [tkestack/kvass#40]
我没有修改prometheus配置，集群也没有增删节点，因此总的series个数没有变化
现在想通过修改max-series来测试prometheus水平扩展能力
发现max-series的配置由大到小时，prometheus副本数会增加，每一个prometheus的series个数满足要求
但是max-series的配置由小到大时，prometheus副本数没有减少（等待了idle时间）
coordinator的配置：--shard.max-series=40000 --shard.delete-pvc=false --shard.max-idle-time=1h --shard.min-shard=1

**Comment by RayHuangCN** [comment]
只有最后一个分片的所有target能转移到前面分片才会触发缩容，这个条件是否满足了？

**Comment by like-inspur** [comment]
什么情况下会触发分片的target转移呢

**Comment by RayHuangCN** [comment]
抱歉，这个issue没及时回答。
缩容将从最后一个分片开始，可缩容条件是分片所有的target都能被他前面的分片所承当。
缩容的过程是先将target全部转移到前面，然后标记分片为空闲，经过一个idle-time后删除。

**Comment by like-inspur** [comment]
那coordinator会定期尝试缩容吗，看最后一个分片的target能否被前面的分片所承当，这个周期是多久尝试一次呢

**Comment by RayHuangCN** [comment]
默认是10秒一次

**Comment by RayHuangCN** [comment]
https://github.com/tkestack/kvass/blob/master/pkg/coordinator/rebalance.go#L360 具体的逻辑在这个函数

**Comment by RayHuangCN** [comment]
这个问题是一个bug导致的，在v0.1.2中已修复
