### ISSUE TITLE
kvass0.1.0 sidecar 日志报错 

### ISSUE THREAD

**Issue by ding-insper** [tkestack/kvass#41]
time="2021-03-11T03:19:22Z" level=info msg="config inject completed" component=injector
2021/03/11 03:20:38 http: proxy error: context canceled
time="2021-03-11T03:21:17Z" level=info msg="config inject completed" component=injector
2021/03/11 03:22:08 http: superfluous response.WriteHeader call from tkestack.io/kvass/pkg/sidecar.(*Proxy).ServeHTTP.func1 (proxy.go:90)
2021/03/11 03:22:38 http: proxy error: context canceled
2021/03/11 03:23:08 http: proxy error: context canceled
2021/03/11 03:23:38 http: proxy error: context canceled
2021/03/11 03:24:08 http: proxy error: context canceled
2021/03/11 03:24:38 http: proxy error: context canceled
2021/03/11 03:25:08 http: proxy error: context canceled
2021/03/11 03:25:38 http: proxy error: context canceled
2021/03/11 03:26:38 http: proxy error: context canceled
2021/03/11 03:26:47 http: superfluous response.WriteHeader call from tkestack.io/kvass/pkg/sidecar.(*Proxy).ServeHTTP.func1 (proxy.go:90)
2021/03/11 03:27:38 http: proxy error: context canceled
2021/03/11 03:28:08 http: proxy error: context canceled
2021/03/11 03:28:27 http: superfluous response.WriteHeader call from tkestack.io/kvass/pkg/sidecar.(*Proxy).ServeHTTP.func1 (proxy.go:90)
2021/03/11 03:28:38 http: proxy error: context canceled
2021/03/11 03:30:44 http: superfluous response.WriteHeader call from tkestack.io/kvass/pkg/sidecar.(*Proxy).ServeHTTP.func1 (proxy.go:90)
2021/03/11 03:30:44 http: superfluous response.WriteHeader call from tkestack.io/kvass/pkg/sidecar.(*Proxy).ServeHTTP.func1 (proxy.go:90)

**Comment by ding-insper** [comment]
curl http://10.222.30.9:8081/api/v1/shard/runtimeinfo   
<a href="/api/v1/shard/runtimeinfo/">Moved Permanently</a>.

**Comment by RayHuangCN** [comment]
应该是采集超时导致的,
