### ISSUE TITLE
数据分片后，告警的最佳方式是什么

### ISSUE THREAD

**Issue by hansedong** [tkestack/kvass#44]
想咨询下，Targets 分片后，告警规则配置在什么地方比较好？
用 Thanos，且 Targets 分片之后，意味着只有通过 Thanos 聚合层查询，才能拿到完整全部的数据。在 TSDB 数据层，通过分片方案降低单 Prometheus 数据压力的方案是很友好的。
但是，Thanos Ruler 官方不是很推荐建议使用 Ruler 来做告警。比如性能、比如查询耗时等，官方建议告警规则，最好是配置在 Prometheus 本身。请问，如果用 Kvass，最佳的告警规则配置方式是什么呢？还是 Thanos Ruler 来配置吗？

**Comment by RayHuangCN** [comment]
我们依旧采用thano ruler来告警，并没有遇到太大的问题。

**Comment by hansedong** [comment]
@RayHuangCN 了解了，感谢
