### ISSUE TITLE
增删job后，coordinator没有下发配置到prometheus

### ISSUE THREAD

**Issue by like-inspur** [tkestack/kvass#45]
增删Job后，coordinator发现了series变化，但是连接prometheus发现异常，导致prometheus没有加载最新的配置
以增加job为例，coordinator一直打印如下日志
```
time="2021-03-26T01:53:22Z" level=info msg="need space 1567" component=coordinator
time="2021-03-26T01:53:22Z" level=warning msg="shard group prometheus-0 is unHealth, skip apply change" component=coordinator
time="2021-03-26T01:53:22Z" level=warning msg="shard group prometheus-1 is unHealth, skip apply change" component=coordinator
time="2021-03-26T01:53:32Z" level=warning msg="config of prometheus-1 is not up to date, expect md5 = 15756264197780680581, shard md5 = 9559724437703473867" component=coordinator
time="2021-03-26T01:53:32Z" level=warning msg="config of prometheus-0 is not up to date, expect md5 = 15756264197780680581, shard md5 = 9559724437703473867" component=coordinator
```
prometheus运行正常，sidecar也没有报错，不知道为什么cooridnator判别prometheus为unHealth

**Comment by RayHuangCN** [comment]
您的Coordinator和Sidecar是否相同版本呢？

**Comment by like-inspur** [comment]
是相同版本0.1.0

**Comment by like-inspur** [comment]
@RayHuangCN 问题依旧存在，对job的增删后，coordinator因为判别prometheus为unhealth，所以不通知prometheus更新配置

**Comment by RayHuangCN** [comment]
这个问题目前还没定位要原因。如果再出现，您是否方便发一下sidecar和coordinator的配置文件呢，因为看日志是2者的配置文件不一致导致的。

**Comment by ArvinChen1991** [comment]
> 增删Job后，coordinator发现了series变化，但是连接prometheus发现异常，导致prometheus没有加载最新的配置
> 以增加job为例，coordinator一直打印如下日志
> 
> ```
> time="2021-03-26T01:53:22Z" level=info msg="need space 1567" component=coordinator
> time="2021-03-26T01:53:22Z" level=warning msg="shard group prometheus-0 is unHealth, skip apply change" component=coordinator
> time="2021-03-26T01:53:22Z" level=warning msg="shard group prometheus-1 is unHealth, skip apply change" component=coordinator
> time="2021-03-26T01:53:32Z" level=warning msg="config of prometheus-1 is not up to date, expect md5 = 15756264197780680581, shard md5 = 9559724437703473867" component=coordinator
> time="2021-03-26T01:53:32Z" level=warning msg="config of prometheus-0 is not up to date, expect md5 = 15756264197780680581, shard md5 = 9559724437703473867" component=coordinator
> ```
> 
> prometheus运行正常，sidecar也没有报错，不知道为什么cooridnator判别prometheus为unHealth

我也出现了同样的问题

**Comment by Felix-YuJing** [comment]
我也遇到了同样的问题。这个问题不解决的话，感觉用不起来。。
```
time="2021-06-02T08:58:17Z" level=warning msg="config of prometheus-for-k8s-replica-0 is not up to date, expect md5 = 17719425448140875177, shard md5 = 8696757463612227254" component=coordinator
time="2021-06-02T08:58:17Z" level=warning msg="shard group prometheus-for-k8s-replica-0 is unHealth, skip apply change" component=coordinator
```

**Comment by like-inspur** [comment]
@RayHuangCN 配置文件是一致的，因为太多这里不发了。请问新版本有没有解决这个问题？

**Comment by RayHuangCN** [comment]
这个应该是external_labels导致的。目前已解决了
