### ISSUE TITLE
0.1.0版本如果一个job的merics数量超过--shard.max-series的设置时，会一直扩容shard实例

### ISSUE THREAD

**Issue by mazhengwei** [tkestack/kvass#46]
场景：10个job，每个job100w+的series，设置的--shard.max-series数量为90w。
现象：kvass会一直调度新增shard来实现分配，但实际并未分配。
影响：扩容到一定程度会导致k8s集群瘫痪。(kvass部署在k8s集群中)。

建议：是否可以增加逻辑判断，对于超过设置阈值的以日志的形式通知提示，并停止这种无效调度。

**Comment by mazhengwei** [comment]
会一直以1000w+的series数量，新增shard实例，但实际无法实现分配，导致集群瘫痪

**Comment by mazhengwei** [comment]
![image](https://user-images.githubusercontent.com/39184810/112742782-17c3c500-8fc4-11eb-88bb-24fa29de4b4c.png)
这是0.4.0版本的日志展示。

**Comment by RayHuangCN** [comment]
非常感谢！！这是个比较严重的bug😣，我们尽快修复。

**Comment by RayHuangCN** [comment]
v0.1.1中已修复这个问题
