### ISSUE TITLE
0.1.0版本target迁移之后，旧shard上的metrics未剔除

### ISSUE THREAD

**Issue by mazwcode** [tkestack/kvass#47]
![image](https://user-images.githubusercontent.com/39184810/112832161-7faf0400-90c7-11eb-8093-ad4cbcfe9a30.png)
shard-38 28分执行迁移，shard-40 series数量的确增加，但3个周期后，shard-38的series没有执行剔除，导致series数量不断增加，增加无故内存消耗。
![image](https://user-images.githubusercontent.com/39184810/112832413-dcaaba00-90c7-11eb-8018-e497a16a69c5.png)
我的理解是：3个周期指的是prometheus拉取三次数据之后，剔除shard-38的数量。
![image](https://user-images.githubusercontent.com/39184810/112832828-73777680-90c8-11eb-9b19-462435690bac.png)

**Comment by RayHuangCN** [comment]
需要等待HEAD落盘周期才会降低下去。这是由Prometheus的落盘机制决定的。

**Comment by mazhengwei** [comment]
落盘周期是2h趴，实际上我这边观察了一天，查看日志是有transfer，但旧shard一直未削减，还会一直新增shard来分配。
背景：1500w+ series，max-shard 90w.
现象：根据换算应该保持在16个shard左右，允许波动；但实际一天下来会一直新增shard，达到50+；导致集群资源不足，采集断层。

**Comment by RayHuangCN** [comment]
在v0.1.1中已尝试修复
