### ISSUE TITLE
关于shard.selector的用法？

### ISSUE THREAD

**Issue by vearne** [tkestack/kvass#5]
现在如果想要达到多副本的目的，是不是只能创建多个`Deployment`了，然后再对--shard.selector=app.kubernetes.io/name=prometheus 传入不同的参数？，但是这样还得部署多个`Deployment`， 感觉不是很优雅，能否提供一个参数，可以选择副本的数量。

**Comment by vearne** [comment]
prometheus 也需要单独创建一套，感觉自动化程度，还是差了一点

**Comment by RayHuangCN** [comment]
非常感谢您的issue😊. 关于这点，我们是考虑了以下几点。
* Kvass其实并不知道分片是否需要特殊配置，例如特殊的annotation,特殊的container等。所以将分片的定义交给使用者，而不是由Kvass创建。

*  为什么副本是部署多个StatefulSet，这个也是考虑了灵活性，因为多个副本的分片配置也可以不一样，例如其中一个副本保持较高可用性，另外一个容忍短暂失败，两者的配置可能不一致。

* 不过您说利用参数选择副本数的能力确实对于部署来说更加方便，我们会考虑加入这个特性！

Kvass目前release了第一个版本，有挺多能力还没开源出来，我们会逐步更新出来，也非常欢迎您继续给我们提建议 ( - :

**Comment by vearne** [comment]
非常感谢。
