### ISSUE TITLE
kvass 里面的各个配置文件意思可以发一下吗，启动需要哪些参数了？

### ISSUE THREAD

**Issue by sunfanwei** [tkestack/kvass#52]
GOROOT=D:\Go #gosetup
GOPATH=D:\goProjects #gosetup
D:\Go\bin\go.exe build -o C:\Users\sWX992771\AppData\Local\Temp\___go_build_coordinator_go_main_go_sidecar_go.exe -gcflags "all=-N -l" D:\goProjects\src\kvass-0.1.2\cmd\kvass\coordinator.go D:\goProjects\src\kvass-0.1.2\cmd\kvass\main.go D:\goProjects\src\kvass-0.1.2\cmd\kvass\sidecar.go #gosetup
"D:\developTools\GoLand 2020.1.3\plugins\go\lib\dlv\windows\dlv.exe" --listen=localhost:57806 --headless=true --api-version=2 --check-go-version=false --only-same-user=false exec C:\Users\sWX992771\AppData\Local\Temp\___go_build_coordinator_go_main_go_sidecar_go.exe -- #gosetup
API server listening at: 127.0.0.1:57806
Kvass is a noninvasive prometheusURL scaling solution,
it allows prometheusURL shard with "target" granules.

Usage:
  Kvass [command]

Available Commands:
  coordinator coordinator manager all prometheus shard
  help        Help about any command
  sidecar     sidecar manager one prometheus shard

Flags:
  -h, --help   help for Kvass

Use "Kvass [command] --help" for more information about a command.

**Comment by RayHuangCN** [comment]
您可以先参考一下example里的。
