### ISSUE TITLE
kvass缺少提供监控信息的metrics

### ISSUE THREAD

**Issue by Felix-YuJing** [tkestack/kvass#59]
比如对以下事件暴露出metrics有助于后期运维监控
```
- 当前need space数量
- 发生change scale事件
- config inject
- target transfer
...

```

**Comment by RayHuangCN** [comment]
新版本正在加入metrics以及一些便于排障的接口，近期会发布出来

**Comment by like-inspur** [comment]
请问sidecar和coordinator都会暴露指标吗

**Comment by RayHuangCN** [comment]
add some metrics in v0.2.0 and continue  to add other in next release

**Comment by Felix-YuJing** [comment]
> add some metrics in v0.2.0 and continue to add other in next release

pretty good

**Comment by like-inspur** [comment]
sidecar暴露的指标和prometheus原生的一样，coordinator没有暴露指标
