### ISSUE TITLE
是否启动prom实例过多？

### ISSUE THREAD

**Issue by vearne** [tkestack/kvass#7]
我发现有很多prom实例上的target是0。但是实际确启动了一堆的prom实例

**Comment by vearne** [comment]
重启集群之后，prometheus的数量会翻倍

**Comment by vearne** [comment]
怀疑，计算实际需要的prom实例数量的算法可能有问题

**Comment by vearne** [comment]
以上问题是prometheus配置了PVC才出现的

**Comment by vearne** [comment]
看了下代码，由于分配target仅仅只依据内存中的信息，如果coordinator发生奔溃，理论上prometheus的数量也会增大一倍。

**Comment by vearne** [comment]
当coordinator重启时，应当先从从所有shard上拿获取一遍target，以便判断config文件中的target是否是新的target。

**Comment by RayHuangCN** [comment]
目前这个问题在0.0.3已经解决了（同时修复了几个已知的bug），问题的原因其实是coordinaor重启的时候，应该先等所有Job都至少得到了一次服务发现结果再进行真正的调度循环，而目前是有任何一次服务发现结果过来就会开始调度，这会导致前几次调度的target集合不全，会认为当前正在抓取的target不在服务发现列表里而将其删除，而后target被发现后又会重新调度，导致异常扩容。

0.0.3版本这周末就会release出来。非常感谢您的issue！:- ）

**Comment by vearne** [comment]
太感谢了，我马上测试一下。

**Comment by vearne** [comment]
现在通过headSeries来衡量整体的负载的方案，也是有问题的。

**Comment by vearne** [comment]
`github.com/tkestack/kvass/pkg/sidecar/service.go`

@@ -143,7 +143,7 @@ func (s *Service) runtimeInfo(g *gin.Context) *api.Result {
                min += r.Series
        }

-       if r.TimeSeriesCount < min {
+       if r.TimeSeriesCount > min {
                r.TimeSeriesCount = min
        }
        return api.Data(&shard.RuntimeInfo{

这里是否改为大于更为合适？

**Comment by vearne** [comment]
```
func (s *Service) runtimeInfo(g *gin.Context) *api.Result {
	r, err := s.getPromRuntimeInfo()
	if err != nil {
		return api.InternalErr(err, "get runtime from prometheus")
	}

	min := int64(0)
	for _, r := range s.getTargetStatus() {
		min += r.Series
	}

	if r.TimeSeriesCount > min { // 我修改了这里
		r.TimeSeriesCount = min
	}
	return api.Data(&shard.RuntimeInfo{
		HeadSeries: r.TimeSeriesCount,
	})
}
```
使用prometheus的TimeSeriesCount是不可靠的，应该使用sidecar的TimeSeriesCount值来衡量shard的负载

**Comment by RayHuangCN** [comment]
这里使用Prometheus最新的time series会更准确一些，因为target的负载会随着时间由些许变动。但是由于target刚下发的时候，Prometheus可能还未开始采集，会导致series数偏低，所以将sidecar的series总和作为最低值参考值。
