### ISSUE TITLE
prometheus 2.28.0支持http的服务发现，kvass现在还不支持。

### ISSUE THREAD

**Issue by aoliang** [tkestack/kvass#70]
prometheus release：https://github.com/prometheus/prometheus/releases/tag/v2.28.0 
issue：#8839

调研试用，希望支持此功能，升级一下prometheus版本，kvass回归验证，重新release。

**Comment by RayHuangCN** [comment]
该功能已在新版本中加入，目前新版本内部在测试中。近期就会放出

**Comment by yangruxi** [comment]
我们目前在最新版本支持了该功能，正在内部测试中，近期会放出

**Comment by aoliang** [comment]
> 我们目前在最新版本支持了该功能，正在内部测试中，近期会放出

谢谢。能给一个大致时间么？

**Comment by yangruxi** [comment]
> > 我们目前在最新版本支持了该功能，正在内部测试中，近期会放出
> 
> 谢谢。能给一个大致时间么？

顺利的话九月下旬

**Comment by RayHuangCN** [comment]
supported in v0.2.0
