### ISSUE TITLE
抓取jmx_exporter metrics问题

### ISSUE THREAD

**Issue by backspace5544** [tkestack/kvass#71]
【问题描述】: 利用promethues/jmx_exporter 以http服务方式 http://ip:port/metrics 暴露服务的jmx信息，然后kvass + thanos + promethues 架构抓取jmx 指标，但是在promethues query 侧却查不到相应的监控指标，已排除可能存在的网络连问题，且自己通过 curl  http://ip:port/metrics 是有指标数据返回的，通过单点promethues 直接配置scrape_config 抓取jmx ，在query 端是可以查到相应的指标数据的；
exporter 吐出的指标类似如下格式：
java_lang_G1_Young_Generation_LastGcInfo_memoryUsageAfterGc_init{type="GarbageCollector",key="CodeHeap 'profiled nmethods'",} 2555904.0
java_lang_G1_Young_Generation_LastGcInfo_memoryUsageAfterGc_init{type="GarbageCollector",key="G1 Old Gen",} 3.154116608E10
java_lang_G1_Young_Generation_LastGcInfo_memoryUsageAfterGc_init{type="GarbageCollector",key="G1 Survivor Space",} 0.0

PS： 很多指标 {} 内部后面都多了一个逗号；
所以，请问下是否是数据格式的原因导致了指标抓取失败？

**Comment by RayHuangCN** [comment]
可以看下日志是否报了格式错误，或者curl 一下 api/v1/targets

**Comment by backspace5544** [comment]
> 可以看下日志是否报了格式错误，或者curl 一下 api/v1/targets
