### ISSUE TITLE
how is the latency in service discovery when a new target is created?

### ISSUE THREAD

**Issue by rokrokss** [tkestack/kvass#8]
I like the concept of this project.
I'm curious about the latency in service discovery when a new target is created.
And in an environment of new deployments are created and destroyed frequently, I think there should be some latency or malfunction in service discovery. And there is the delay in prometheus when reloading config I guess?

**Comment by RayHuangCN** [comment]
kvass do targets distribution every 10s by default, so the max latency is about 10s by default. 
you can set --coordinator.interval to change it.
