### ISSUE TITLE
coordinate config文件上限

### ISSUE THREAD

**Issue by HaoKunT** [tkestack/kvass#89]
请问一下coordinate对于配置文件很大的情况有相关测试吗？比如说在多少个采集配置的情况下会出现更新target卡顿等？

**Comment by RayHuangCN** [comment]
配置文件很大是因为写了很多static的吗，我们有case是写了3000多个静态target，更新target并没有出现明显延迟

**Comment by HaoKunT** [comment]
> 配置文件很大是因为写了很多static的吗，我们有case是写了3000多个静态target，更新target并没有出现明显延迟

类似这种情况

我理解kvass的coordinate是会去探测每个target有多少个时间线，那当target过多的时候，会不会每一次探测花费的时间过多，造成更新延迟。
